github: [HyperCodec, stdcout1, bruh1273, sugisaru, tangykiwi, xrexy, smoke-wolf, santigamedev, rickytheracc, raccoondog, jancantcode, florianmichael, cmordusmor, 0x3c50, 0x4d2d]
custom: https://tungstenclient.com/donation
